name: Veracode Release Candidate SAST Workflow

on:
  workflow_call:
    inputs:
      profile-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      veracode-api-id:
        required: true
      veracode-api-key:
        required: true
        
jobs:
  platform-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: ${{inputs.artifact-name}}
          # Destination path
          path: ${{github.workspace}}
          
      - name: Current Directory
        run: pwd
      - name: Confirm Contents
        run: ls -la
        
      - name: Veracode Upload And Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
            # appname
            appname: ${{inputs.profile-name}}
            # createprofile
            createprofile: true
            # filepath
            filepath: ${{github.workspace}}\application.zip
            # version
            version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
            # vid
            vid: ${{secrets.veracode-api-id}}
            # vkey
            vkey: ${{secrets.veracode-api-key}}
            # true or false
            createsandbox: true
            # name of the sandbox
            sandboxname: 'Release Candidate'
            # wait X minutes for the scan to complete
            # scantimeout: # optional
            # modules to exclude from module selection
            # exclude: # optional
            # modules to include in module selection
            # include: # optional
            # business criticality - policy selection
            # criticality: # optional
            # filename pattern
            # pattern: # optional
            # replacement
            # replacement: # optional
            # specify to scan in a sandbox
            # sandboxid: # optional
            # All top level modules
            # scanallnonfataltoplevelmodules: # optional
            # platform selected modules
            # selected: # optional
            # selected modules like from previous scan
            # selectedpreviously: # optional
            # teams
            # teams: # optional
            # teams
            # toplevel: # optional
            # automatically delete the current scan if there are any errors when uploading files or starting the scan
            # deleteincompletescan: # optional
            # specify version of the Java API Wrapper; default is latest
            # javawrapperversion: # optional
            # show detailed diagnostic information, which you can use for debugging, in the output.
            # debug: # optional
